### ISSUE TITLE
Добавить фильтр для com_contact

### ISSUE THREAD

**Issue by Septdir** [Joomline/JlContentFieldsFilter#11]
В com_contact такие же доп поля, так что сделать на фильтр и для них не такая большая проблема

**Comment by Arkadiy-Sedelnikov** [comment]
Думаешь у кого-то контактов столько, что их необходимо фильтровать?

**Comment by Septdir** [comment]
Ну тут дело, не в количестве, даже 3 интема иногда нужно фильтровать.
com_contact хороший компонент для списка сотрудников, и я несколько раз натыкался на задачи сделать там фильтрацию. особенно в медицинской тематике

**Comment by zikkuratvk** [comment]
Ну в целом, то да контакты сейчас по сути выступают в роли профилей пользователя.

**Comment by Arkadiy-Sedelnikov** [comment]
Да не проблема, можно и для контактов сделать. Только сначала надо проверить новую фильтрацию и сделать pr в джумлу.

**Comment by Septdir** [comment]
@Arkadiy-Sedelnikov  Ну фильтрацию я проверил. А pr главное чтобы приняли. Хотя по идеи должны принять ибо это все таки не тригер, а просто передача sate ещё и стандартного. 

Кстати сделай отдельную ветку без переопределения модели. Чтобы можно было спокойно тестировать pr

Если pr включат в релиз, то нужно будет сделать проверку на версию движка. Чтобы если версия меньше подключалось переопределение. 
А то у нас народ не особо любит движок обновлять.

**Comment by Arkadiy-Sedelnikov** [comment]
Ок, тогда сейчас сделаю pr и иже с ними.

**Comment by Arkadiy-Sedelnikov** [comment]
Сделал pr https://github.com/joomla/joomla-cms/pull/19819

**Comment by Septdir** [comment]
Ну будем ждать результата.

**Comment by Arkadiy-Sedelnikov** [comment]
Посмотрел в модель контактов, там тоже никаких зацепок нет для фильтрации. Только с хаком/подменой.

**Comment by Septdir** [comment]
@Arkadiy-Sedelnikov Ну а кто сказал что будет очень легко.

**Comment by Arkadiy-Sedelnikov** [comment]
В том-то и дело, что проще всего самостоятельно решать проблемы любыми подручными средствами. А с джумлоделами бодаться прямо болото какое-то.

**Comment by Septdir** [comment]
@Arkadiy-Sedelnikov Ну одно другому не мешает. Сделать с переопределением, а там примут pr то с com_content можно будет снять. Как говориться на других надейся а сам не плошай.

**Comment by Arkadiy-Sedelnikov** [comment]
Чет мне кажется что не примут. Никто не спорит, не доказывает свою точку зрения, просто слились и тишина...

**Comment by Septdir** [comment]
@Arkadiy-Sedelnikov Все может быть, уже лучше отказ, чем зависший PR.
А поспорить ну мы поспорили немного, а дальше не нам решать. Да и pr создан в преддверии релиза. так что тишина вполне ожидаема.

**Comment by Arkadiy-Sedelnikov** [comment]
bfb87ddf01666e3f554b4e4d5b0c9cf676c83040
