### ISSUE TITLE
Попрваить ReadMe

### ISSUE THREAD

**Issue by Septdir** [Joomline/JlContentFieldsFilter#12]
> Пока дистрибутив не собран вы можете собрать его и установить модуль и плагин сами. Для этого заархивируйте отдельно содержимое папки mod_jlcontentfieldsfilter и папки plg_system_jlcontentfieldsfilter, установите оба дистрибутива, опубликуйте плагин, опубликуйте и настройте модуль.

Не актуально после
https://github.com/Joomline/JlContentFieldsFilter/commit/17ee62476758f4b5df09d4a8db3b741279b98877

**Comment by Arkadiy-Sedelnikov** [comment]
5303e854198a15d159ac5b891415155cd52858dc
