### ISSUE TITLE
Поправить нотис в модуле

### ISSUE THREAD

**Issue by Septdir** [Joomline/JlContentFieldsFilter#13]
Если в модуле не выбрана категория выход нотис
Notice: Undefined offset: 0 in /modules/mod_jlcontentfieldsfilter/mod_jlcontentfieldsfilter.php on line 42

Либо вообще возвращать  false(= пустой модуль) если полей нет.

**Comment by Arkadiy-Sedelnikov** [comment]
Джумшоппинг мешает отлавливать ошибки. Там искусственно понижается уровень показа ошибок, если его восстановить, то на джумшоппинге ничего не сделать, вот и резвимся :)

**Comment by Septdir** [comment]
Ну поднять по соседству еще одну копию joomla ни когда не помешает.

**Comment by Arkadiy-Sedelnikov** [comment]
e6fb3c212b125600622e07096b8d86389b5f4650
