### ISSUE TITLE
XMLHttpRequest устаревший метод

### ISSUE THREAD

**Issue by zikkuratvk** [Joomline/JlContentFieldsFilter#14]
Пользователь сообщает, о том что консоль ругается на устаревший метод.
https://joomline.net/ru/forum/jlcontentfieldsfilter/6163-xmlhttprequest.html

**Comment by Arkadiy-Sedelnikov** [comment]
Это не относится к нашему расширению. Во первых jQuery.ajax() по умолчанию асинхронный, во вторых если убрать вставку загруженного содержимого в html страницы, то это предупреждение пропадает, следовательно проблема не в наших методах, а в загруженном содержимом.
