### ISSUE TITLE
Пустое value

### ISSUE THREAD

**Issue by kernusr** [Joomline/JlContentFieldsFilter#15]
Заметил интересную особенность - если передать пустое value для чекбокса или радиобаттона, то фильр возвращает 0 итемов.

**Comment by Arkadiy-Sedelnikov** [comment]
Фильтр ищет соответсвия если присутствует параметр. Если пустому значению параметра ничего не соответствует, то выборка пустая. Для того чтобы чекбоксы и радио не участвтали в выборке их надо все сделать неотмеченными.

**Comment by kernusr** [comment]
при таком раскладе возникает неудобная ситуация, если "косячат" сессии.
Сбросить параметр фильтрации получается только передав пустой параметр.

**Comment by Arkadiy-Sedelnikov** [comment]
Могу отсеивать пустые значения при фильтрации. Так пойдет?

**Comment by kernusr** [comment]
Как мне кажется, так логичнее поступать. Зачем передавать в запрос пустое значение?
Кстати, то, что в настройках полей джумлы, можно сохранить поле без значения - глупость полнейшая. Как можно выводить checkbox и radio без value.

**Comment by Arkadiy-Sedelnikov** [comment]
14594868a25f6d0b6bd889a8800dd26ff3a37bbb
