### ISSUE TITLE
Множественный выбор radio

### ISSUE THREAD

**Issue by kernusr** [Joomline/JlContentFieldsFilter#16]
В чём сакральный смысл передавать радиобаттоны, как array? Множественный выбор радио ;)?

**Comment by Arkadiy-Sedelnikov** [comment]
Унификация :) 
На самом деле не знаю в чем, но разницы для запроса практически нет.

**Comment by Arkadiy-Sedelnikov** [comment]
Радио в фильтре может выводиться чекбоксами со всеми вытекающими.
