### ISSUE TITLE
reset form not working

### ISSUE THREAD

**Issue by zikkuratvk** [Joomline/JlContentFieldsFilter#17]
https://joomline.net/ru/forum/jlcontentfieldsfilter/6183-reset-form-not-working-planed-extension.html#7245

**Comment by AlekVolsk** [comment]
при аякс-фильтрации при сбросе флажка в группе checkboxes фильтр не сбрасывает параметр, кнопка сброса формы не работает

**Comment by Arkadiy-Sedelnikov** [comment]
У меня почему-то работает. См. http://poligon3.argens.ru/index.php?option=com_content&view=category&layout=blog&id=11&filter_tag[0]=&Itemid=401 логин/пароль poligon3
Модуль с аяксом находится ниже модуля без аякса.

**Comment by Arkadiy-Sedelnikov** [comment]
b5f5dfa95a1d7074c296563a0cef7af37b2a3b11
