### ISSUE TITLE
Фильтр инпута значение от и до 

### ISSUE THREAD

**Issue by zikkuratvk** [Joomline/JlContentFieldsFilter#18]
Многие стали использовать поля для каталогов. и возникла проблема, что многим хочется фильтровать по цене, значения от и до.
Пример человек создает поле инпут и указывает там 10, 20, 25, 30, 40 допустим это квадратным метры жилья.
После этого он хочет увидеть значения от и до допустим с 20 до 30 квадратов.

Так же очень актуальна фильтрация по цене в связи с появлением вот этой корзинки https://joomlaforum.ru/index.php/topic,345981.0.html

**Comment by Arkadiy-Sedelnikov** [comment]
Все данные полей лежат в текстовом поле, из-за этого все фильтрации больше, меньше или между могут работать некорректно.

**Comment by AlekVolsk** [comment]
Как правило в админке для подобных значений используется тип поля "целое (integer)", что помогает исключить ввод значений с ненужными пробелами и прочими сторонними символами, при этом в запросе вроде как можно указать в условии целое число и текстовые поля корректно обрабатываются, проверял на varchar, но хз, как поведет себя на text

**Comment by AlekVolsk** [comment]
Также удобно было бы при формировании параметра фильтра получать минимальные и максимальные значения поля для указанной категории

**Comment by Septdir** [comment]
Проблема не типе поля, а в типе столбца БД где лежит значение `value` в  `#__fields_values`.  Оно `text`.
И горький подсказывает что когда тип столбца не числовое значение (к примеру int или double)  between работает абы как. То бишь сделать то можно. Ибо база позволяет. Но вот за корректность такого фильтра ни кто не поручиться.

*По мню когда с выборкой для карты возился заметил эту неприятнейшую особенность*

**Comment by Arkadiy-Sedelnikov** [comment]
Можно попробовать приведение типов в запросе https://phpclub.ru/mysql/doc/cast-functions.html

**Comment by Arkadiy-Sedelnikov** [comment]
2dc36258f1146c0d5854482e1c817f80e9a66140
