### ISSUE TITLE
reset the filter and pagination problem

### ISSUE THREAD

**Issue by Sukinoz** [Joomline/JlContentFieldsFilter#20]
See the video:
https://drive.google.com/file/d/1KdWEIq_ZRV-aHaZIiOZaXz6_8jtabMRG/view

**Comment by AlekVolsk** [comment]
Вот снова проблема с пагинатором, о которой говорили в личке, смотрели с другого конца, но с тем же результатом: фильтр при изменении состояния не сохраняет позицию пагинатора, при этом урл (на видео не видно) при аякс-отправке сохраняет состояние пагинации

**Comment by Arkadiy-Sedelnikov** [comment]
Hi. I have such a problem not there is. Which version of the filter do you have installed? Joomla cache enabled? And if enabled, what type?

**Comment by Sukinoz** [comment]
default.demojoomla.com
support
N0VHS8Lybk9N

**Comment by Arkadiy-Sedelnikov** [comment]
Disabled module caching and the problem was solved.

**Comment by Sukinoz** [comment]
Great.

PD: Maybe it should be included in the documentation
