### ISSUE TITLE
Фильтр по заголовку материала

### ISSUE THREAD

**Issue by zikkuratvk** [Joomline/JlContentFieldsFilter#21]
Просят добавить фильтр по заголовку материала, то есть по сути это то же поле инпута, только фильтрует только по Title Материала.

Ссылка на тему форума:
https://joomline.net/ru/forum/jlcontentfieldsfilter/6199-search-filter-by-article-tittle-and-content.html#7280

**Comment by Arkadiy-Sedelnikov** [comment]
Сомневаюсь я что-то. У нас фильтр по дополнительным полям, думаешь стоит рушить концепцию? Сейчас в фильтрации принимает участие одна таблица, нагрузка довольно оптимальна. Чтобы фильтровать еще и по заголовку придется подключать еще одну таблицу. Нагрузка возрастет, а смысл какой? Есть стандартный поиск джумлы который прекрасно ищет по заголовкам. Да и к поиску по заголовку уже дополнительных полей и не надо т.к. заголовок сущность очень индивидуальная.

**Comment by zikkuratvk** [comment]
Отклонено
