### ISSUE TITLE
Добавить отключаемое предупреждение об фильтрации

### ISSUE THREAD

**Issue by zikkuratvk** [Joomline/JlContentFieldsFilter#22]
Предложили добавить настройку, предупреждения, что вы просматриваете отфильтрованный контент.
https://joomline.net/ru/forum/jlcontentfieldsfilter/6198-an-user-friendly-filtered-message.html#7279

**Comment by Arkadiy-Sedelnikov** [comment]
Это не знаю, нужно ли. Слишком мало тех кому это пригодится.

**Comment by zikkuratvk** [comment]
Согласен что избыточны.
