### ISSUE TITLE
Сброс фильтра при переходе в другую категорию

### ISSUE THREAD

**Issue by zikkuratvk** [Joomline/JlContentFieldsFilter#23]
Есть баг, сброса фильтра, при переходе в другую категорию, точнее он не сбрасывает, хотя в целом должен сбрасывать.
https://joomline.net/ru/forum/jlcontentfieldsfilter/6197-auto-reset-filtered-articles.html#7278

**Comment by Arkadiy-Sedelnikov** [comment]
http://poligon3.argens.ru/test-cat и http://poligon3.argens.ru/test-cat-2
Все сбрасывается, видимо опять кэш джумлы.
