### ISSUE TITLE
Сео фильтр

### ISSUE THREAD

**Issue by zikkuratvk** [Joomline/JlContentFieldsFilter#24]
При включенной настройки фильтра GET, чтоб менялся тайтл в зависимости от настроек фильтра. То есть у нас есть название категории - параметр фильтра 1 - параметр фильтра - 2

**Comment by zikkuratvk** [comment]
Ну тебе может быть не надо... )) а мне допустим надо. Тем более это же очень сильно расширяет возможную семантику, для каталогов это очень хорошо.

**Comment by kernusr** [comment]
Как показала практика подобных решений на Битриксе - генерация заголовков фильтром - не самое лучшее решение.
Во-первых - не все поля нужны в заголовке
Во-вторых - как быть со склонением слов
В-третьих - я филтрую кирпичи. У меня есть поля "Цвет кирпича" и "Материал кирпича". Как это в заголовке будет выглядеть? Грубо говоря, "Купить кирпич цвет кирпича красный, материал кирпича глина"?
Тут либо городить велосипедище с настройкой. либо делать отдельным плагином.

**Comment by zikkuratvk** [comment]
Ну допустим категория Кирпичи.
Фильтруем по типу Цвет кирпича (предположим цвет красный). 
выглядеть значит так будет Кирпичи - цвет кирпича: Красный.
Если мы выбираем два цвета.
Кирпичи - цвет кирпича: Красный, желтый
Если выбираем тип кирпича глина 
Кирпичи - цвет кирпича: Красный - тип кирпича: Глина.

**Comment by kernusr** [comment]
@Septdir , ну как сказать... Очень даже выгодно в каталогах делать страницы с результатами фильтрации каноничными и даже в sitemap их прописывать. Это позволяет покрыть гораздо большее количество целевых запросов и, при этом, не плодить категории и теги. Как плюс - автоматически генерируется title и description. А можно ещё и СЕО-текст в тело выводить, при определённых фильтрах.
Допустим, мы торгуем всё теми же кирпичами. Кирпичи у нас классифицированы в разделах, по производителям и назначению. Даль ше мы не стали заморачиваться с созданием разделов, а возложили эту нелёгкую задачу на наш фильтр. Таким образом мы можем покрыть запросы вида:

- "Кирпич BRAER" (всё понятно - получаем страницу из радела каталога)
- "Кирпич BRAER строительный" или "Кирпич BRAER облицовочный" (опять же из раздела)
- "Кирпич строительный" или "Кирпич облицовочный" (уже по фильтру, т.к. у нас может быть много производителей кирпича)
- "Кирпич облицовочный керамический жёлтый" (очень даже нехилый запорс и покрывается он фильтром)

Я тут пытаюсь объяснить не то, что это не нужно в принципе. Я пытаюсь донести, что это не нужно рядовому обывателю, использующему фильтрацию. Построение заголовков для фильтра - очень нужный функционал, но он достоен вынесения в отдельный плагин, расширяющий функционал фильтра. Ну и построение самих заголовков - та ещё задачка. То, что предложил Вадим, не очень хорошо покроет поисковые запросы, а городить кучу настроек - лишнее усложнение элегантного решения, коим является данный модуль.

**Comment by Septdir** [comment]
@kernusr Все вами описанное делается микроразметкой. Либо действительно отдельными страницами, на своем компоненте. Чтобы не было громоздких категорий. 

Фильтр на то и фильтр чтобы просто отсетить лишнее на странице. А не получить новую страницу. Поэтому и страницы с отфильтровываемыми итемами не каноничны. Можно и примеры крупных магазинов привести. Где товары от определенных производителей хоть и чаще всего выводятся через фильтр. По факту являются "под-категориями" и имеют отдельную страницу, для поисковиков.

Что касается остального то тут и плагин сделать сложно. и дело не в механике, в ней то ничего сложно. Получил что нужно передал в тайтл то что нужно и готово, есть пролема в последовательностью, но решаема. Тут проблема в том что это слишком индивидуально. Если и делать такое то в крайнем случае в шаблоне.

А по факту писать компонент. Который будет все делать за вас. да и в сайтмап добавлять можно.

**Comment by kernusr** [comment]
> Фильтр на то и фильтр чтобы просто отсетить лишнее на странице. А не получить новую страницу. Поэтому и страницы с отфильтровываемыми итемами не каноничны. Можно и примеры крупных магазинов привести.

Ну, как бы вот https://market.yandex.ru/catalog/56179/list?track=pieces&glfilter=7893318%3A152794&onstock=1&local-offers-first=1
http://joxi.ru/gmv9lejsxp6eLr
http://joxi.ru/MAj9BMRsvV6d62
http://joxi.ru/5md3BWGuvxRJnr

Подобным пользуется Я.Маркет. Попадал на такое в Юлмарте и Ситилинке. Т.е. они отдают в поиск страницы, применённым фильтром. Это нормальная практика.

**Comment by AlekVolsk** [comment]
> Допустим, мы торгуем всё теми же кирпичами. Кирпичи у нас классифицированы в разделах, по производителям и назначению. Даль ше мы не стали заморачиваться с созданием разделов, а возложили эту нелёгкую задачу на наш фильтр. Таким образом мы можем покрыть запросы вида...

Подобное принято делать отдельными посадочными или тематическими лендингами, возможно со своими фильтрами

Любая отфильтрованная страница априори неканонична

**Comment by zikkuratvk** [comment]
Ну как раз для больших каталогов это очень нужный функционал. Сеошники наоборот думают, как конкретищировать  страницу. Чтоб страница максимально точно отвечала на запрос.

**Comment by AlekVolsk** [comment]
Вадим, для этого 
1) надо поменять сеошника, думающего реалиями 7-10 летней давности
2) урлы должны быть уже не на гетах, а полноценные, что малореально в условиях данного решения

**Comment by Septdir** [comment]
@kernusr 
>Подобным пользуется Я.Маркет. Попадал на такое в Юлмарте и Ситилинке. Т.е. они отдают в поиск страницы, применённым фильтром. Это нормальная практика.

Я процитирую сам себя

> Можно и примеры крупных магазинов привести. Где товары от определенных производителей хоть и чаще всего выводятся через фильтр. По факту являются "под-категориями" и имеют отдельную страницу, для поисковиков.

Вот тот же твой пример из яндекса. (в юлматре та же система)  
Если я вобью в поиск `Наушники и Bluetooth-гарнитуры JBL проводные`  
То в выдаче увижу `Наушники и Bluetooth-гарнитуры JBL` А не  `Наушники и Bluetooth-гарнитуры JBL проводные`

То бишь хоть эти страницы и имеют url с параметрами фильтром 7893318 по факту это реально отдельные страницы. 

У юлмарта это сделано даже получше в плане sef и более наглядно к примеру [вот](https://www.ulmart.ru/catalog/notebooks/brand_msi)
На эту страницу можно попасть через поисковик и если еще индексировать результат при фильтрации категории ноутбуку, то будут дубли, Кстати если выбрать там в верхнем меню под категорию `Замена игрового ПК` то попадем на такую страницу [Замена настольного ПК MSI](https://www.ulmart.ru/catalog/notebooks_5202_349898/brand_msi)


Но это относиться только к категориям. А не к фильтру в целом (то бишь там нет `Кирпич облицовочный керамический жёлтый`). Кстати даже далеко ходит не надо. Фильтр категорий joomla. Может отображать как на текущей странице при помощи фильтра. Так и на отдельной странице при помощи роута/пункта.  И если не сделать каноническую страницу будет дубль.

Страницу фильтра без прямой ссылки или сайтмапы поисковик даже не увидит ибо поисковик не будет отправлять форму. 

Такого можно добиться и на joomla. Не уверен насчет готовых компонентов в своем компоненте такое сделать не составит проблемы. Однако все это затачивает под конкретный сайт. Ну кончено же. Это ни каким боком не нужно в com_content. который для блога предназначен.

Поводя итог. Могу сказать не стоит путать фильтры с категориями, даже если категория и структура в целом создается автоматически.

Ну вроде все разжижал.

**Comment by AlekVolsk** [comment]
В общем, Вадим, овчинка выделки не стОит. Если делать - то полноценную сео-кастомизацию, а не только заголовки, иначе нет смысла дергаться

**Comment by Septdir** [comment]
@AlekVolsk 
>  урлы должны быть уже не на гетах, а полноценные, что малореально в условиях данного решения

Не мало вероятно а не возможно, ибо придется лезть в роут, а это черевато. 

@zikkuratvk 
>Ну как раз для больших каталогов это очень нужный функционал. Сеошники наоборот думают, как конкретищировать страницу. Чтоб страница максимально точно отвечала на запрос.

Они еще думают какие именно страницы делать отдельными а какие нет. Поэтому грубо говоря. что-то разграничиваться категориями, что-то тэгами, а что-то фильтр по доп полям.

Закладывается это еще при построении структуры сайта.

**Comment by zikkuratvk** [comment]
То что далек от идеала фильтр я согласен, но он становится лучше и функциональней. 
По сути сейчас не хватает только отключения несуществующих параметров. Это из глобального.

Что касается serf ссылок не sef я лично такой проблемы не наблюдал... В основном поисковикам побарабану. Мы вот недавно увеличили количество страниц сайт до 3.5 лямов это позволило увеличить трафик в 3 раза... И количество людей растет постоянно... Мы надеемся что к концу года за счет этого увеличится трафик в 7-8 раз. Глупо не пользоваться всеми возможными методами для привлечения пользователей.

**Comment by Septdir** [comment]
@zikkuratvk Я сделал с точностью на оборот, отрезав кучу под категорий и поднялся в поиске, да и трафик подрос.  Но опять таки это все конкретные случаи. На массу же да еще и плагине фильтра. Получиться только хуже.

Как передать нужные фильтры в поисковик и сайтмапу? 
Как настроить какие фильтры нужны для поиска а какие нет?
Как избавиться от дублей, то бишь чтобы какие фильтры были каноничны а какие нет.

Если это все решить, то все система получиться тяжелой, да и все равно не гибкой.

Принцип прост, если тебе нужно чтобы страница в поиске, то она и должна быть страницей. А как ты ее сделаешь это уже дело 10. Хочешь LP и там модулем выводит итемы. Хочешь категорию. Хочешь тэг. (Это если про com_content говорить)

Если уж и делать автоматизацию подобного, то явно не на com_content плюс пара десятков плагинов. А просто взять и написать нормальный шоп, кстати с такими настройками и построением структуры, может получиться неплохой компонент

**Comment by exmmth** [comment]
Если делать, то по следующему принципу:
Нужно чтобы было интерфейс для конечного набора создать sef url исходя из конкретного набора выбранных параметров фильтра. По тому же принципу предлагалась автогенерация этих наборов. Для набора можно было менять 1 url, 2 title, 3 keywords, 4 description, 5 og-тети(). 
Отсюда следует, что под это подходит компонент, а в сам модуль не добавлять.
