### ISSUE TITLE
Не объявлена переменная в хелпере

### ISSUE THREAD

**Issue by zikkuratvk** [Joomline/JlContentFieldsFilter#30]
https://joomline.net/ru/forum/jlcontentfieldsfilter/6245-error-with-version-1-6.html

**Comment by AlekVolsk** [comment]
и не должна быть объявлена
шаблоны полей надо указать заново в каждом поле, я писал об этом

**Comment by zikkuratvk** [comment]
Решено релиз 1.6.1
