### ISSUE TITLE
Настройка скрывать модуль если не категория

### ISSUE THREAD

**Issue by zikkuratvk** [Joomline/JlContentFieldsFilter#33]
Тоже просили такую настройку.
Так как в некоторых случаях фильтр хотят выводить только в категории Joomla, где непосредственно материалы.

**Comment by AlekVolsk** [comment]
также необходимо скрывать модуль, если в категории нет опубликованных материалов, но сама категория почему-то выводится

**Comment by Arkadiy-Sedelnikov** [comment]
Так у нас на других страницах и не выводится. Или я что-то забыл?

**Comment by zikkuratvk** [comment]
По моему выводится в материалах.

**Comment by Arkadiy-Sedelnikov** [comment]
d68b1810252cf72c790b5baa5ce847e4d4d36e91
