### ISSUE TITLE
Изображение спиннера

### ISSUE THREAD

**Issue by AlekVolsk** [Joomline/JlContentFieldsFilter#4]
Добавить возможность указать собственное изображение спиннера, вместо ajax_loader.gif, в т.ч формата svg

**Comment by Arkadiy-Sedelnikov** [comment]
c972e97c15008b0033c6fc0fc6f2a8bc5a098e86

**Comment by AlekVolsk** [comment]
ага, а размер всегда 32 фиксом? не айс

**Comment by Arkadiy-Sedelnikov** [comment]
1c000069944983b6c730dac969b0af93c153a5a3
