### ISSUE TITLE
Состояние поля чекбоксов по умолчанию

### ISSUE THREAD

**Issue by AlekVolsk** [Joomline/JlContentFieldsFilter#43]
Для UX требуется, чтобы в поле чекбоксов были выбраны все флажки по умолчанию, т.к. показ материалов происходит именно по выбранным флажкам.

https://joomlaforum.ru/index.php/topic,350451.msg1782264.html#msg1782264

**Comment by AlekVolsk** [comment]
Дополнительно: поле списка (select) и поле переключателей (radio) имеют обязательную доп.опцию - отображать всё

**Comment by Arkadiy-Sedelnikov** [comment]
Плохая идея. Когда ничего не выбрано, логично, что по этому параметру не фильтруется. Если сделать все выбранным, то пользователю придется сделать больше движений для выбора нужной комбинации т.к. сначала ему придется все сбросить, а только потом выбирать то, что ему нужно.

**Comment by AlekVolsk** [comment]
доп.кнопки "вкл.всё"/"выкл.всё"

**Comment by AlekVolsk** [comment]
опять же, это по идее должно быть опционально

**Comment by Arkadiy-Sedelnikov** [comment]
Кнопки вкл и выкл сделать можно, но я понимю UX как удобство использования, а удобнее кликнуть один раз чем два. Возрази мне если я не прав.
