### ISSUE TITLE
Значения range если материалы в подктегории

### ISSUE THREAD

**Issue by zikkuratvk** [Joomline/JlContentFieldsFilter#44]
Если материалы находятся в корневой категории... то все фильтруется без проблем.
Если же материалы в подкатегории, то фильтрация происходит, но мы не знаем пределы значений.

https://s.mail.ru/JD6F/5ZSvg49zq

Что предлагаю? Добавить опцию в модуль "Получать значения из подкатегорий", при ее включении,  выборака идет из всех подкатегорий текущей категории. 

Пример.

Категория 1 - мы тут
- Категория 2
- Категорий 3
-- Категория 4
- Категория 5

Значения выбираются из категорий с 1 по 5ую.

Категория 1 
- Категория 2
- Категорий 3 - мы тут
-- Категория 4 
- Категория 5

Значения выбираются из категорий 3-4.

**Comment by Arkadiy-Sedelnikov** [comment]
По моему надо задействовать настройку контента, позволяющую выводить материалы из подкатегорий в категории, а не делать свою.

**Comment by zikkuratvk** [comment]
Ну можно и от туда кстати взять этот момент.

**Comment by zikkuratvk** [comment]
38ea39581f9131541f4413c384657e36f3ebff43 проверил все работает.
