### ISSUE TITLE
Support SQL field type?

### ISSUE THREAD

**Issue by andykirk** [Joomline/JlContentFieldsFilter#48]
Hi, 
Apologies if this has been asked before - I couldn't find anything.

Are there any plans to include support for the SQL field type?
If not I could have a go myself and create a PR if you like (though any pointers would be appreciated).

Thanks,
Andy

**Comment by zikkuratvk** [comment]
There are no plans for such a possibility yet. If there is a ready implementation, we are ready to consider it for inclusion in extensions.
