### ISSUE TITLE
[Идея] Добавления в фильтр прямо в com_fields

### ISSUE THREAD

**Issue by Septdir** [Joomline/JlContentFieldsFilter#5]
Собственно, эту идею хотел использовать у себя в каталоге, но сейчас нет ни времени ни надобности, поэтому решил поделиться.

## Суть
Дать возможность пользователям выбирать поля для фильтрации прямо в com_fields при создании\ре датировании конкретного поля.

## Набросок реализации
Через системный плагин (который уже есть) используя тригер `onContentPrepareForm` (думаю объяснять как это делать не нужно). Цепляемся к имени формы и context параметру в url  добавляем поле (ну к примеру вы падающий список) `Фильтр` с параметрами
* Нет (не добавляется в модуль)
* Список
* Radio
Ну и т.д

Затем уже в самом модуле определяем категорию и выводим нужные поля.

## Плюсы
Не придется лазить каждый раз в модуль. Один раз создал, вывел и все меняется само

## Минусы
Теряется гибкость. К примеру если поля доступно для двух категорий, то и в фильтре будет выводиться\ не выводиться в обеих одинаково.

Ну расписал, как мог. Реализация не сложная и особых подводных камней нет.

**Comment by Arkadiy-Sedelnikov** [comment]
Игорь, спасибо за идею, подумаю над реализацией.

**Comment by Arkadiy-Sedelnikov** [comment]
Готово. 42389163a63bd2ff7a188ef77dde2ff234b328bf
