### ISSUE TITLE
Текст если нет материалов в категории

### ISSUE THREAD

**Issue by zikkuratvk** [Joomline/JlContentFieldsFilter#50]
Если в результате фильтрации в категории не оказывается материалов, то выводится просто пустая область, предлагают сделать вывод сообщения, что "По вашему запросу ничего не найдено".

https://joomline.net/ru/forum/jlcontentfieldsfilter/6361.html

**Comment by AlekVolsk** [comment]
Для такого случая есть штатное сообщение, говорящее об отсутствии материалов в данной категории, можно переопределить его. Однако необходимо порою для каждой категории выводить собственное значение, например, в магазине одежды в категории платьев вывести 
**"К сожалению, не нашлось ни одного платья, удовлетворяющего параметрам фильтра."**
в категории кроссовок вывести соответствующее сообщение об отсутствии кроссовок, при этом категория может быть пуста и без фильтрации, тогда сообщение необходимо немного другое.

**Суть вопроса**: продумать возможность для каждой категории выводить 2 вида индивидуальных сообщений: когда категория пуста и когда она не пуста, но нет ничего, удовлетворяющего параметрам фильтрации; при этом, если не задан индивидуальный тест сообщения - брать заданный универсальный, подходящий для всех категорий, задаваемый к примеру в параметрах модуля.

**Comment by Arkadiy-Sedelnikov** [comment]
Это не к нам. Фильтр только фильтрует материалы. выводом фильтруемого занимается com_content. Вот там и надо колдовать над этими надписями.

**Comment by AlekVolsk** [comment]
Поскольку фильтр переопределяет модель категории com_content, то возможно уместно реализовать в переопределённой модели функцию проверки, почему список пуст: потому что условия фильтрации или потому что категория действительно пуста. Это позволит более свободно колдовать над выводом сообщений в макетах категорий.
