### ISSUE TITLE
Проблема с удалением значений из поля от и до.

### ISSUE THREAD

**Issue by zikkuratvk** [Joomline/JlContentFieldsFilter#55]
![image](https://user-images.githubusercontent.com/2261206/85589369-cc9b1100-b643-11ea-9eda-9c7a1e6f970e.png)

удаляем из поля ОТ или из поля ДО цифру и все скидывается в NaN, при фильтрации следовательно вызывается ошибка. Необходима обработка, чтоб нельзя было указать пустое значение и недопустимое, то есть должна быть только цифра.

такая же проблем возникает если в поле вбить текст или какие то спец символы.

**Comment by dmitriitux** [comment]
ок, поправлю

**Comment by AlekVolsk** [comment]
#59
