### ISSUE TITLE
Показывать в списочных полях только те варианты, значения которых присутствуют в материалах

### ISSUE THREAD

**Issue by AlekVolsk** [Joomline/JlContentFieldsFilter#6]
Для полей списочного типа (список, селект, группы чекбоксов, рабиобаттоны) добавить возможность отображать в фильтре только те значения, которые указаны хотя бы в одном материале, в идеале - для каждого поля в отдельности.
Например: группа чекбоксов отображает размер обуви: 36, 37, 38, 39 и так далее, но ни в одном материале не указано наличие размера 38, следовательно это значение в фильтре не отображать.

**Comment by AlekVolsk** [comment]
Допускаю, что возникнет доп.нагрузка при определении наличия значения в базе, возможно имеет смысл рассмотреть при установке/обновлении модуля создание индексов в базе с целью оптимизации, благо на эти индексы не влияют обновы J

**Comment by Septdir** [comment]
@AlekVolsk даже с индексами будет доп нагрузка, если и делать то только через ajax.
Как вариант заодно и отображать кол-во итемов попадающих под условия фильтрации

**Comment by Arkadiy-Sedelnikov** [comment]
Кол-во итемов попадающих под условия фильтрации существенно проще сделать и легче для сервера. Видимо на этом остановлюсь.

**Comment by progreccor** [comment]
Очень нужная функция. Есть новости?

**Comment by kernusr** [comment]
Учитывая, что корзина для материалов появилась, фильтр "от и до" сделали - на материалах можно клепать простенький каталог. 
Целесообразно было бы и отключение отсутствующих значений прикрутить.

**Comment by AlekVolsk** [comment]
#59
