### ISSUE TITLE
Возможность для каждого поля указать собственный шаблон вывода

### ISSUE THREAD

**Issue by AlekVolsk** [Joomline/JlContentFieldsFilter#7]
Реализовать возможность для каждого поля независимо от его типа указать собственный шаблон вывода (из основного шаблона сайта или из самого модуля)

**Comment by Arkadiy-Sedelnikov** [comment]
Уже есть. Скачай мастер и установи. настройки вывода полей в фильтре переместились в настройки самих полей.

**Comment by AlekVolsk** [comment]
По-прежнему актуально: в настройках поля добавлен выбор типа поля, но нет выбора индивидуального шаблона.
К примеру: есть 3 поля типа checkboxes, но для каждого поля нужен свой шаблон: в одном случае вывести checkboxes в 2 колонки, в другом случае нужно вывести не все флажки из списка, а только первые 7 (из 30), в третьем случае список надо спрятать внутрь дропдауна. Шаблон написать индивидуально под место не проблема, но как его применить к каждому конкретному случаю?
