### ISSUE TITLE
cannot declare class categorymodel in joomla 4.0

### ISSUE THREAD

**Issue by myousefi1368** [Joomline/JlContentFieldsFilter#74]
Hi
When I use cw multicategory plugin with jlcontentfields filter together in joomla 4.0 i face to this error:
cannot declare class joomla\component\content\site\model\categorymodel, because the name is already in use

What should i do?
In joomla 3 i use them together but now i want to migrate to joomla 4

Please help...

**Comment by zikkuratvk** [comment]
Hello. Probably the plugin overrides the Joomla article model, which causes a conflict. In this case, we can't help. Will this error occur in Joomla 4 is not known.

**Comment by myousefi1368** [comment]
> Hello. Probably the plugin overrides the Joomla article model, which causes a conflict. In this case, we can't help. Will this error occur in Joomla 4 is not known.

Yes multicategory plugin has a category model like jlcontentfieldsfilter.
I merge jlcontentfieldsfilter category model with cw multicategory and remove load model line in jlcontentfieldsfilter.
Now jlcontentfieldsfilter and cw multicategory works in joomla 4.0

Bu if we could solve this problem in better way its much better.
any suggestions...

**Comment by AlekVolsk** [comment]
> any suggestions...

For both plugins, make a PR in which implement support for both plugins in one model and check: for the filter plugin - if the multicategory plugin is installed and it is loaded earlier, do not redefine the model again in the filter plugin, for the multicategory plugin - vice versa

**Comment by myousefi1368** [comment]
> 

many plugins might use joomla 4.0 content models.
In joomla 3 there was no problem that how many plugins use the models but in figure out that in joomla 4.0 we can't use two plugins that use content models.
I want to know, really there isn't a better way that developers of plugins use for joomla 4?
So if the answer is no, we should tell all developers of plugins that support themselves!!!

i think there is a better way...
