### ISSUE TITLE
ARIA IDs are not unique

### ISSUE THREAD

**Issue by web-eau-net** [Joomline/JlContentFieldsFilter#79]
Hi guys,

I use your module here: [templatejoomla.com](https://templatejoomla.com) 

Checking the page with Google Pagespeed gives an error in accessibility because ARIA IDs that are not unique
[Google Pagespeed report](https://pagespeed.web.dev/report?url=https%3A%2F%2Ftemplatejoomla.com%2F&hl=en)

Do you plan to add a fix in the next release, please? 
Thanks in advance and once again, keep on the good work guys !

**Comment by sergeytolkachyov** [comment]
@web-eau-net hi. i found that module default layout didn't have an ARIA-attributes at all. Have you solved this issue?

**Comment by web-eau-net** [comment]
Hey Sergey :)
In fact, the issue was located 50 cms in front of the screen, not in the extension...
Sorry ;)
